
import Predictionary from 'predictionary'

async function SetupAutocomplete() {
    const topWords = [
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "I",
        "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
        "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
        "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
        "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
        "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
        "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
        "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
        "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
        "is", "much", "where", "very", "those", "need", "here", "such", "without", "own",
        "each", "too", "still", "both", "between", "while", "through", "during", "before", "being",
        "until", "against", "though", "might", "himself", "few", "really", "off", "above", "far",
        "away", "down", "always", "something", "why", "never", "last", "under", "same", "another",
        "does", "around", "every", "must", "doesn't", "yes", "going", "help", "asked",
        "went", "looking", "give", "walk", "again", "little", "long", "great", "old", "next",
        "should", "years", "came", "show", "set", "put", "large", "end", "world", "school",
        "place", "small", "home", "hand", "part", "found", "different", "thought", "took",
        "right", "still", "three", "state", "once", "move", "general", "sure", "heart", "among",
        "air", "stood", "given", "later", "open", "government", "ever", "order", "land", "turn",
        "morning", "run", "kept", "face", "fact", "group", "play", "stand", "increase", "early",
        "course", "change", "help", "line", "city", "close", "case", "force", "meet",
        "once", "water", "upon", "war", "build", "hear", "light", "unite", "live", "every",
        "country", "bring", "center", "let", "side", "try", "god", "head", "own",
        "page", "should", "found", "answer", "grow", "study", "learn", "plant", "cover", "food",
        "sun", "four", "thought", "let", "keep", "eye", "point", "book", "word", "real",
        "story", "since", "ever", "ago", "saw", "stop", "least", "seem", "idea", "room",
        "power", "often", "rather", "young", "across", "always", "white", "sea", "watch", "until",
        "car", "example", "night", "tree", "child", "less", "enough", "mind", "ask", "family",
        "mother", "big", "better", "question", "reason", "person", "door", "sure", "such", "hope",
        "thank", "best", "problem", "call", "business", "woman", "life", "thing", "week",
        "company", "system", "program", "work", "number", "night", "important", "water",
        "call", "move", "pay", "right", "national", "level", "expect", "able", "second", "late",
        "tell", "write", "provide", "money", "service", "friend", "kind", "sure", "however", "student",
        "month", "drive", "change", "history", "buy", "probably", "hold", "happen", "specific", "type",
        "either", "several", "high", "research", "paper", "particular", "girl", "guy", "century", "eat",
        "die", "produce", "market", "possible", "necessary", "stay", "figure", "result", "speak",
        "especially", "return", "phone", "decision", "current", "ground", "fall", "note", "lead", "listen",
        "table", "product", "almost", "office", "social", "music", "consider", "appear", "actually",
        "probably", "human", "wait", "serve", "die", "send", "expect", "sense", "build",
        "stay", "fall", "oh", "nation", "plan", "cut", "college", "interest", "death", "course",
        "form", "likely", "type", "certainly", "reach", "remain", "suggest", "class", "control", "raise",
        "care", "perhaps", "break", "society", "experience", "behind", "ago", "hard", "talk", "health",
        "whether", "act", "view", "report", "true", "language", "along", "situation",
        "lead", "watch", "today", "husband", "almost", "father", "wall", "fire", "bit", "lose",
        "begin", "finally", "hour", "read", "feel", "effect", "picture", "clear", "practice", "piece",
        "land", "recent", "describe", "store", "certain", "street", "artist", "six",
        "war", "computer", "maybe", "performance", "pressure", "seven", "create", "bad",
        "similar", "love", "quality", "project", "name", "area", "law", "least", "ago",
        "situation", "sorry", "son", "hope", "able", "political", "minute", "rate", "true",
        "black", "check", "special", "complete", "natural", "concern", "amount", "outside", "fine",
        "member", "effort", "once", "million", "everything", "position", "information", "positive", "subject",
        "half", "technology", "individual", "color", "list", "simple", "tax", "decade", "herself",
        "policy", "image", "phone", "road", "trade", "group", "death", "morning", "situation",
        "difference", "material", "east", "single", "letter", "condition", "choice", "place", "single",
        "daughter", "administration", "south", "husband", "floor", "campaign", "material", "population", "economy",
        "medical", "hospital", "church", "risk", "fire", "future", "wrong", "involve", "defense",
        "anyone", "increase", "security", "bank", "myself", "certainly", "sport", "board", "seek",
        "per", "subject", "officer", "private", "rest", "behavior", "deal", "performance", "fight",
        "throw", "top", "quickly", "past", "goal", "bed", "order", "author", "fill",
        "represent", "focus", "foreign", "drop", "blood", "upon", "agency", "push", "nature",
        "recently", "store", "multiple", "begin", "price", "cause", "legal", "public", "various",
        "white", "district", "direction", "feed", "attempt", "practice", "agree", "brother", "workshop",
        "quickly", "onto", "master", "teacher", "parent", "offer", "activity", "reflect", "instead",
        "wish", "strength", "original", "bar", "measure", "somebody", "specific", "success", "argue",
        "identify", "growth", "loss", "degree", "wonder", "attack", "region", "television", "box",
        "training", "pretty", "trade", "election", "everybody", "physical", "general", "feeling", "standard",
        "bill", "message", "fail", "outside", "arrive", "analysis", "benefit", "sex", "forward",
        "lawyer", "memory", "wear", "career", "catch", "station", "treat", "trip", "evening",
        "inside", "management", "professional", "mission", "strong", "complex", "project", "hit", "total",
        "client", "image", "cultural", "traditional", "mission", "violence", "skill", "relatively", "post",
        "variety", "administration", "sign", "sort", "ten", "southern", "committed", "understanding", "approach",
        "serious", "determine", "resource", "democratic", "production", "commercial", "leader", "bit", "mouth",
        "series", "pain", "plan", "possibility", "recognize", "block", "opinion", "original", "farm",
        "remind", "leg", "supply", "kill", "indeed", "safe", "session", "officer", "element",
        "flat", "sales", "object", "finger", "garden", "notice", "collection", "modern", "task",
        "partner", "positive", "vote", "stage", "science", "blue", "strategy", "clearly", "discuss",
        "station", "audience", "add", "film", "contact", "crew", "hair", "behavior", "energy",
        "solid", "wood", "unique", "whatever", "walk", "pattern", "beauty", "fear", "animal",
        "unit", "combination", "competition", "existing", "totally", "basic", "ring", "zone", "soil",
        "grant", "pleasure", "aware", "middle", "presence", "definitely", "establishment", "weight", "slow",
        "band", "arm", "relative", "aside", "association", "vehicle", "mile", "immediately", "term",
        "finance", "letter", "mouth", "facility", "pair", "reader", "literature", "faith", "profit",
        "remove", "edge", "born", "index", "sleep", "manage", "simply", "ignore", "network",
        "application", "okay", "avenue", "intention", "collection", "solution", "forest", "explain", "income",
        "popular", "speech", "cost", "disease", "final", "damage", "entire", "skill", "manner",
        "meaning", "adult", "survey", "escape", "damn", "limited", "rich", "team", "ahead",
        "glass", "discussion", "bridge", "train", "lady", "perfectly", "improve", "emotional", "deputy",
        "climate", "struggle", "ground", "construction", "charity", "disaster", "entertainment", "error", "format",
        "introduction", "operation", "pension", "opportunity", "driver", "flight", "metal", "length", "entirely"
    ];

    return new Promise(async (resolve) => {
        try {
            window.predictionary = Predictionary.instance();
            window.predictionary.addWords(topWords);
        } catch (error) {
            console.error('Error setting up autocomplete:', error);
            resolve(); 
        }
    });
}

export default SetupAutocomplete;